ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter disp_dev,$(USEMODULE)))
  USEMODULE += st77xx
endif

ifneq (,$(filter st77xx,$(USEMODULE)))
  # indicate that a ST7735 is used
  USEMODULE += st7735
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  FEATURES_REQUIRED += periph_spi_on_qspi
  USEMODULE += mtd_spi_nor
endif

# setup the samd21 arduino bootloader related dependencies
include $(RIOTBOARD)/common/samdx1-arduino-bootloader/Makefile.dep
